/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER-PC
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jButton21.setEnabled(false);
        jButton18.setEnabled(false);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton10.setEnabled(false);
        jButton12.setEnabled(false);
        jButton13.setEnabled(false);
        jButton14.setEnabled(false);
        jButton20.setEnabled(false);
        jButton19.setEnabled(false);
        jButton22.setEnabled(false);
        jButton23.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();

        jButton11.setText("jButton11");

        jButton9.setText("jButton9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jLabel1.setText("電腦");

        jLabel2.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jLabel2.setText("玩家");

        jLabel3.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jLabel3.setText("籌碼數");

        jLabel4.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jLabel5.setText("籌碼數");

        jLabel6.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jLabel7.setText("本局當前下注");

        jLabel8.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jLabel8.setText("本局當前下注");

        jLabel9.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        jButton1.setText("下底注");

        jButton2.setText("翻倍下注");

        jButton3.setText("3倍下注");

        jButton4.setText("4倍下注");

        jButton5.setText("ALL IN");

        jButton6.setText("放棄");

        jButton7.setText("下底注");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("翻倍下注");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setText("4倍下注");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.setText("ALL IN");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("放棄");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("3倍下注");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        jButton15.setText("低");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jLabel22.setText("電腦難度");

        jButton16.setText("中");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("高");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButton18.setText("新局");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jLabel23.setText("minmum bet: 20");

        jLabel24.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jLabel24.setText("BONUS:");

        jLabel25.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel25.setText("royal straight flush x20");

        jLabel26.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel26.setText("straight flush x10");

        jLabel27.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel27.setText("four of a kind x5");

        jLabel28.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        jButton19.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jButton19.setText("pass");

        jButton20.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jButton20.setText("pass");

        jButton21.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButton21.setText("開始");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("新細明體", 0, 24)); // NOI18N

        jButton22.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jButton22.setText("下一張牌");

        jButton23.setText("下一輪");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton20)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton15)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton16)
                                        .addGap(30, 30, 30)
                                        .addComponent(jButton17))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4))
                                    .addComponent(jButton19))
                                .addContainerGap(69, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel27))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(638, 638, 638)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(jButton6)
                        .addComponent(jButton19)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jButton15)
                            .addComponent(jButton16)
                            .addComponent(jButton17))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(jButton21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jButton23))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7)
                            .addComponent(jButton10)
                            .addComponent(jButton8)
                            .addComponent(jButton14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton13)
                            .addComponent(jButton12)
                            .addComponent(jButton20))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int card[]= new int [6];//牌
    int point[]=new int [4];//花色
    int computercard[]=new int[5];
    int computerpoint[]=new int[5];//電腦牌堆
    int playercard[]=new int[5];
    int playerpoint[]=new int[5];//玩家牌堆
    int newplayercard,newcomputercard,playerbet=500,computerbet=500,playerbetnow=20,computerbetnow=20,difficult,cardcount=0,allin=0;//玩家和電腦新抽的牌,玩家和電腦的籌碼,本輪下注,難度,第幾輪牌,紀錄有沒有人喊allin
    int computerstatus,playerstatus;//紀錄是否在pass狀態pass狀態設為0底注設1,翻倍設2,3倍設3,4倍設4,ALLIN設5,若電腦後手也設0
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int a=0,b=0,c=0,d=0,cont=0,aa=0,bb=0,cc=0,dd=0,rcardcount;//單字儲存牌疊字儲存花色,存cardcount
        rcardcount=cardcount;
        jLabel29.setText("玩家ALLIN");
        playerbetnow=playerbet;
        jLabel21.setText(String.valueOf(playerbetnow));
        playerstatus=5;
        if (computerstatus==0){
           for(int g=0;rcardcount>g;rcardcount--){
               switch(cont){
                   case 0:
                           aa=computerpoint[rcardcount];
                           a=computercard[rcardcount];
                           break;
                   case 1:
                           bb=computerpoint[rcardcount];
                           b=computercard[rcardcount];
                           break;
                   case 2:
                           cc=computerpoint[rcardcount];
                           c=computercard[rcardcount];
                           break;
                   case 3:
                           dd=computerpoint[rcardcount];
                           d=computercard[rcardcount];
                           break;
               }
               cont++;
           }
           if(difficult==3){
               if(cont==3){
                   if(a==b&&c==d&&b==c){//four of akind
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbet;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                   else if((((a==10||b==10||c==10||d==10)&&(a==11||b==11||c==11||d==11)&&(a==12||b==12||c==12||d==12)&&(a==13||b==13||c==13||d==13))||(((a==1||b==1||c==1||d==1)&&(a==11||b==11||c==11||d==11)&&(a==12||b==12||c==12||d==12)&&(a==13||b==13||c==13||d==13)))||(((a==10||b==10||c==10||d==10)&&(a==11||b==11||c==11||d==11)&&(a==12||b==12||c==12||d==12)&&(a==1||b==1||c==1||d==1)))||(((a==10||b==10||c==10||d==10)&&(a==11||b==11||c==11||d==11)&&(a==1||b==1||c==1||d==1)&&(a==13||b==13||c==13||d==13)))||(((a==10||b==10||c==10||d==10)&&(a==1||b==1||c==1||d==1)&&(a==12||b==12||c==12||d==12)&&(a==13||b==13||c==13||d==13))))&&(aa==bb&&cc==dd&&bb==cc)){//royal straight flush
                       if(computerbet<200){
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbet;
                       }
                       else{
                           jLabel29.setText("電腦放棄");
                           playerbet=playerbet*2;
                           computerbet=computerbet-computerbetnow;
                           computerbetnow=0;
                           playerbetnow=0;
                           jLabel6.setText(String.valueOf(playerbet));
                           jLabel28.setText(String.valueOf(computerbet));
                           jButton23.setEnabled(true);
                           jLabel9.setText(null);
                           jLabel21.setText(null);
                       }
                   }
                   else if((a==b&&b==c)||(b==c&&c==d)||(a==c&&c==d)||(a==b&&b==d)){//full house or three of a kind or four of a kind
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbet;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                   else{//小牌就放棄不跟
                       jLabel29.setText("電腦放棄");
                       playerbet=playerbet*2;
                       computerbet=computerbet-computerbetnow;
                       computerbetnow=0;
                       playerbetnow=0;
                       jLabel6.setText(String.valueOf(playerbet));
                       jLabel28.setText(String.valueOf(computerbet));
                       jButton23.setEnabled(true);
                       jLabel9.setText(null);
                       jLabel21.setText(null);
                   }
               }
               else if(cont==2){
                   if(a==b&&b==c){//three of kind or four of a kind or full house
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbet;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                   else{
                       jLabel29.setText("電腦放棄");
                       playerbet=playerbet*2;
                       computerbet=computerbet-computerbetnow;
                       computerbetnow=0;
                       playerbetnow=0;
                       jLabel6.setText(String.valueOf(playerbet));
                       jLabel28.setText(String.valueOf(computerbet));
                       jButton23.setEnabled(true);
                       jLabel9.setText(null);
                       jLabel21.setText(null);
                   }
                }
               else if(cont==1){
                       jLabel29.setText("電腦放棄");
                       playerbet=playerbet*2;
                       computerbet=computerbet-computerbetnow;
                       computerbetnow=0;
                       playerbetnow=0;
                       jLabel6.setText(String.valueOf(playerbet));
                       jLabel28.setText(String.valueOf(computerbet));
                       jButton23.setEnabled(true);
                       jLabel9.setText(null);
                       jLabel21.setText(null);
               }
              
           }
           else if(difficult==2){
               if(cont==3){
                   if(a==b&&c==d&&b==c){//four of akind
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbet;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                   else if((((a==10||b==10||c==10||d==10)&&(a==11||b==11||c==11||d==11)&&(a==12||b==12||c==12||d==12)&&(a==13||b==13||c==13||d==13))||(((a==1||b==1||c==1||d==1)&&(a==11||b==11||c==11||d==11)&&(a==12||b==12||c==12||d==12)&&(a==13||b==13||c==13||d==13)))||(((a==10||b==10||c==10||d==10)&&(a==11||b==11||c==11||d==11)&&(a==12||b==12||c==12||d==12)&&(a==1||b==1||c==1||d==1)))||(((a==10||b==10||c==10||d==10)&&(a==11||b==11||c==11||d==11)&&(a==1||b==1||c==1||d==1)&&(a==13||b==13||c==13||d==13)))||(((a==10||b==10||c==10||d==10)&&(a==1||b==1||c==1||d==1)&&(a==12||b==12||c==12||d==12)&&(a==13||b==13||c==13||d==13))))&&(aa==bb&&cc==dd&&bb==cc)){//royal straight flush
                       if(computerbet<200){
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbet;
                       }
                       else{
                           jLabel29.setText("電腦放棄");
                           playerbet=playerbet*2;
                           computerbet=computerbet-computerbetnow;
                           computerbetnow=0;
                           playerbetnow=0;
                           jLabel6.setText(String.valueOf(playerbet));
                           jLabel28.setText(String.valueOf(computerbet));
                           jButton23.setEnabled(true);
                           jLabel9.setText(null);
                           jLabel21.setText(null);
                       }
                   }
                   else if((a==b&&b==c)||(b==c&&c==d)||(a==c&&c==d)||(a==b&&b==d)){//full house or three of a kind or four of a kind
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbet;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                   else if((aa==bb)&&(bb==cc)&&(cc==dd)){
                       //flush
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbet;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                   else{//小牌就放棄不跟//straight也不賭
                       jLabel29.setText("電腦放棄");
                       playerbet=playerbet*2;
                       computerbet=computerbet-computerbetnow;
                       computerbetnow=0;
                       playerbetnow=0;
                       jLabel6.setText(String.valueOf(playerbet));
                       jLabel28.setText(String.valueOf(computerbet));
                       jButton23.setEnabled(true);
                       jLabel9.setText(null);
                       jLabel21.setText(null);
                   }
               }
               else if(cont==2){
                   if(a==b&&b==c){//three of kind or four of a kind or full house
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbet;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                   else{
                       jLabel29.setText("電腦放棄");
                       playerbet=playerbet*2;
                       computerbet=computerbet-computerbetnow;
                       computerbetnow=0;
                       playerbetnow=0;
                       jLabel6.setText(String.valueOf(playerbet));
                       jLabel28.setText(String.valueOf(computerbet));
                       jButton23.setEnabled(true);
                       jLabel9.setText(null);
                       jLabel21.setText(null);
                   }
                }
               else if(cont==1){
                       jLabel29.setText("電腦放棄");
                       playerbet=playerbet*2;
                       computerbet=computerbet-computerbetnow;
                       computerbetnow=0;
                       playerbetnow=0;
                       jLabel6.setText(String.valueOf(playerbet));
                       jLabel28.setText(String.valueOf(computerbet));
                       jButton23.setEnabled(true);
                       jLabel9.setText(null);
                       jLabel21.setText(null);
               }
           }
           else{
               jLabel29.setText("電腦跟了");
               computerbetnow=computerbet;
               jLabel9.setText(String.valueOf(computerbetnow));
               computerstatus=1;
           }
       }
        jButton22.setEnabled(true);
        computerstatus=1;
        jButton20.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton10.setEnabled(false);
        jButton12.setEnabled(false);
        jButton13.setEnabled(false);
        jButton14.setEnabled(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        jLabel29.setText("玩家放棄");
        playerbet=playerbet-playerbetnow;
        computerbet=computerbet+playerbetnow;
        jLabel6.setText(String.valueOf(playerbet));
        jLabel28.setText(String.valueOf(computerbet));
        jLabel9.setText(null);
        jLabel21.setText(null);
        playerbetnow=0;
        computerbetnow=0;
        jButton23.setEnabled(true);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton10.setEnabled(false);
        jButton12.setEnabled(false);
        jButton13.setEnabled(false);
        jButton14.setEnabled(false);
        jButton20.setEnabled(false);
        computerstatus=1;
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        difficult=1;
        jLabel30.setText("難度:低");
        jButton21.setEnabled(true);
        jButton15.setEnabled(false);
        jButton16.setEnabled(false);
        jButton17.setEnabled(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        difficult=2;
        jLabel30.setText("難度:中");
        jButton21.setEnabled(true);
        jButton15.setEnabled(false);
        jButton16.setEnabled(false);
        jButton17.setEnabled(false);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        difficult=3;
        jLabel30.setText("難度:高");
        jButton21.setEnabled(true);
        jButton15.setEnabled(false);
        jButton16.setEnabled(false);
        jButton17.setEnabled(false);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        jButton18.setEnabled(true);
        jLabel6.setText(String.valueOf(playerbet));
        jLabel28.setText(String.valueOf(computerbet));
        //決定第一輪誰先下注
        if (computercard[1]>playercard[1]){
            if(difficult==3){
                if(computercard[0]==computercard[1]){//如果拿到對子  
                  jLabel29.setText("computerpass");//先pass看玩家狀況
                  computerstatus=0;
                  jButton7.setEnabled(true);
                  jButton8.setEnabled(true);
                  jButton10.setEnabled(true);
                  jButton12.setEnabled(true);
                  jButton13.setEnabled(true);
                  jButton14.setEnabled(true);
                }
                else if(computerpoint[0]==computerpoint[1]){//如果同花
                  jLabel29.setText("computerpass");//先pass看玩家狀況
                  computerstatus=0;
                  jButton7.setEnabled(true);
                  jButton8.setEnabled(true);
                  jButton10.setEnabled(true);
                  jButton12.setEnabled(true);
                  jButton13.setEnabled(true);
                  jButton14.setEnabled(true);
                }
                else{//烏龍牌
                  jLabel29.setText("電腦下底注");
                  computerbetnow=20;
                  jLabel9.setText(String.valueOf(computerbetnow));
                  computerstatus=1;
                  jButton7.setEnabled(true);
                  jButton8.setEnabled(true);
                  jButton10.setEnabled(true);
                  jButton12.setEnabled(true);
                  jButton13.setEnabled(true);
                  jButton14.setEnabled(true);
                }
            }
            else if(difficult==2){
                 if(computercard[0]==computercard[1]){  
                  jLabel29.setText("computerpass");//先pass看玩家狀況
                  computerstatus=0;
                  jButton7.setEnabled(true);
                  jButton8.setEnabled(true);
                  jButton10.setEnabled(true);
                  jButton12.setEnabled(true);
                  jButton13.setEnabled(true);
                  jButton14.setEnabled(true);
                }
                else if(computerpoint[0]==computerpoint[1]){
                  jLabel29.setText("電腦下底注");
                  computerbetnow=20;
                  jLabel9.setText(String.valueOf(computerbetnow));
                  computerstatus=1;
                  jButton7.setEnabled(true);
                  jButton8.setEnabled(true);
                  jButton10.setEnabled(true);
                  jButton12.setEnabled(true);
                  jButton13.setEnabled(true);
                  jButton14.setEnabled(true);
                }
                else{
                  jLabel29.setText("電腦下底注");
                  computerbetnow=20;
                  jLabel9.setText(String.valueOf(computerbetnow));
                  computerstatus=1;
                  jButton7.setEnabled(true);
                  jButton8.setEnabled(true);
                  jButton10.setEnabled(true);
                  jButton12.setEnabled(true);
                  jButton13.setEnabled(true);
                  jButton14.setEnabled(true);
                }
            }
            else{
                  jLabel29.setText("電腦下底注");
                  computerstatus=1;
                  jButton7.setEnabled(true);
                  jButton8.setEnabled(true);
                  jButton10.setEnabled(true);
                  jButton12.setEnabled(true);
                  jButton13.setEnabled(true);
                  jButton14.setEnabled(true);
            }
        }
        else if(computercard[1]==playercard[1]){//如果同花
            if(computerpoint[1]>playerpoint[1]){ 
                if(difficult==2||difficult==3){
                  jLabel29.setText("computerpass");//先pass看玩家狀況
                  computerstatus=0;
                  jButton7.setEnabled(true);
                  jButton8.setEnabled(true);
                  jButton10.setEnabled(true);
                  jButton12.setEnabled(true);
                  jButton13.setEnabled(true);
                  jButton14.setEnabled(true);
                }
                else{
                  jLabel29.setText("電腦下底注");
                  computerstatus=1;
                  jButton7.setEnabled(true);
                  jButton8.setEnabled(true);
                  jButton10.setEnabled(true);
                  jButton12.setEnabled(true);
                  jButton13.setEnabled(true);
                  jButton14.setEnabled(true);
                }
            }
            else{
                computerstatus=0;
                jButton7.setEnabled(true);
                jButton8.setEnabled(true);
                jButton10.setEnabled(true);
                jButton12.setEnabled(true);
                jButton13.setEnabled(true);
                jButton14.setEnabled(true);
                jButton20.setEnabled(true);
            }
        }
        else{
            computerstatus=0;
            jButton7.setEnabled(true);
            jButton8.setEnabled(true);
            jButton10.setEnabled(true);
            jButton12.setEnabled(true);
            jButton13.setEnabled(true);
            jButton14.setEnabled(true);
            jButton20.setEnabled(true);
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      int a=0,b=0,c=0,d=0,cont=0,aa=0,bb=0,cc=0,dd=0,rcardcount;//單字儲存牌疊字儲存花色,存cardcount
        jLabel29.setText("玩家下底注");
        playerbetnow=playerbetnow;
        jLabel21.setText(String.valueOf(playerbetnow));
        playerstatus=1;
        if (computerstatus==0){
        jLabel29.setText("電腦下底注");
        computerstatus=1;
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton10.setEnabled(true);
        jButton12.setEnabled(true);
        jButton13.setEnabled(true);
        jButton14.setEnabled(true);
        computerstatus=1;}
        else{
        jButton22.setEnabled(true);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton10.setEnabled(false);
        jButton12.setEnabled(false);
        jButton13.setEnabled(false);
        jButton14.setEnabled(false);
        jButton20.setEnabled(false);}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       int a=0,b=0,c=0,d=0,cont=0,aa=0,bb=0,cc=0,dd=0,rcardcount;//單字儲存牌疊字儲存花色,存cardcount
        jLabel29.setText("玩家翻倍底注");
        playerstatus=2;
        rcardcount=cardcount;
        playerbetnow=playerbetnow+20*2;
        if (computerstatus==0){
           for(int g=0;rcardcount>g;rcardcount--){
               switch(cont){
                   case 0:
                           aa=computerpoint[rcardcount];
                           a=computercard[rcardcount];
                           break;
                   case 1:
                           bb=computerpoint[rcardcount];
                           b=computercard[rcardcount];
                           break;
                   case 2:
                           cc=computerpoint[rcardcount];
                           c=computercard[rcardcount];
                           break;
                   case 3:
                           dd=computerpoint[rcardcount];
                           d=computercard[rcardcount];
                           break;
               }
               cont++;
           }
       }
        jButton22.setEnabled(true);
        computerstatus=1;
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton10.setEnabled(false);
        jButton12.setEnabled(false);
        jButton13.setEnabled(false);
        jButton14.setEnabled(false);
        jButton20.setEnabled(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        int a=0,b=0,c=0,d=0,cont=0,aa=0,bb=0,cc=0,dd=0,rcardcount;//單字儲存牌疊字儲存花色,存cardcount
        jLabel29.setText("玩家翻3倍底注");
        playerstatus=3;
        rcardcount=cardcount;
        if (computerstatus==0){
           for(int g=0;rcardcount>g;rcardcount--){
               switch(cont){
                   case 0:
                           aa=computerpoint[rcardcount];
                           a=computercard[rcardcount];
                           break;
                   case 1:
                           bb=computerpoint[rcardcount];
                           b=computercard[rcardcount];
                           break;
                   case 2:
                           cc=computerpoint[rcardcount];
                           c=computercard[rcardcount];
                           break;
                   case 3:
                           dd=computerpoint[rcardcount];
                           d=computercard[rcardcount];
                           break;
               }
               cont++;
           }
       }
        jButton22.setEnabled(true);
        computerstatus=1;
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton10.setEnabled(false);
        jButton12.setEnabled(false);
        jButton13.setEnabled(false);
        jButton14.setEnabled(false);
        jButton20.setEnabled(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int a=0,b=0,c=0,d=0,cont=0,aa=0,bb=0,cc=0,dd=0,rcardcount;//單字儲存牌疊字儲存花色,存cardcount
        jLabel29.setText("玩家翻4倍底注");
        playerstatus=4;
        rcardcount=cardcount;
        playerbetnow=playerbetnow+20*4;
        if (computerstatus==0){
           for(int g=0;rcardcount>g;rcardcount--){//讀牌出來
               switch(cont){
                   case 0:
                           aa=computerpoint[rcardcount];
                           a=computercard[rcardcount];
                           break;
                   case 1:
                           bb=computerpoint[rcardcount];
                           b=computercard[rcardcount];
                           break;
                   case 2:
                           cc=computerpoint[rcardcount];
                           c=computercard[rcardcount];
                           break;
                   case 3:
                           dd=computerpoint[rcardcount];
                           d=computercard[rcardcount];
                           break;
               }
               cont++;
           }
       
           if(difficult==3){
               if(cont==3){
                   if(a==b&&c==d&&b==c){//four of akind
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbetnow+20*4;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                   else if((((a==10||b==10||c==10||d==10)&&(a==11||b==11||c==11||d==11)&&(a==12||b==12||c==12||d==12)&&(a==13||b==13||c==13||d==13))||(((a==1||b==1||c==1||d==1)&&(a==11||b==11||c==11||d==11)&&(a==12||b==12||c==12||d==12)&&(a==13||b==13||c==13||d==13)))||(((a==10||b==10||c==10||d==10)&&(a==11||b==11||c==11||d==11)&&(a==12||b==12||c==12||d==12)&&(a==1||b==1||c==1||d==1)))||(((a==10||b==10||c==10||d==10)&&(a==11||b==11||c==11||d==11)&&(a==1||b==1||c==1||d==1)&&(a==13||b==13||c==13||d==13)))||(((a==10||b==10||c==10||d==10)&&(a==1||b==1||c==1||d==1)&&(a==12||b==12||c==12||d==12)&&(a==13||b==13||c==13||d==13))))&&(aa==bb&&cc==dd&&bb==cc)){//royal straight flush
                       if(computerbet<600){
                       jLabel29.setText("電腦跟了");
                      computerbetnow=computerbetnow+20*4;
                       }
                       else{
                           jLabel29.setText("電腦放棄");
                           playerbet=computerbetnow+playerbet;
                           computerbet=computerbet-computerbetnow;
                           computerbetnow=0;
                           playerbetnow=0;
                           jLabel6.setText(String.valueOf(playerbet));
                           jLabel28.setText(String.valueOf(computerbet));
                           jButton23.setEnabled(true);
                           jLabel9.setText(null);
                           jLabel21.setText(null);
                       }
                   }
                   else if((a==b&&b==c)||(b==c&&c==d)||(a==c&&c==d)||(a==b&&b==d)){//full house or three of a kind or four of a kind
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbetnow+20*4;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                   else if((aa==bb)&&(bb==cc)&&(cc==dd)){//flush
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbetnow+20*4;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                   else{//小牌就放棄不跟
                       jLabel29.setText("電腦放棄");
                       playerbet=computerbetnow+playerbet;
                       computerbet=computerbet-computerbetnow;
                       computerbetnow=0;
                       playerbetnow=0;
                       jLabel6.setText(String.valueOf(playerbet));
                       jLabel28.setText(String.valueOf(computerbet));
                       jButton23.setEnabled(true);
                       jLabel9.setText(null);
                       jLabel21.setText(null);
                   }
               }
               else if(cont==2){
                   if(a==b&&b==c){//three of kind or four of a kind or full house
                       jLabel29.setText("電腦跟了");
                      computerbetnow=computerbetnow+20*4;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                   
                   else{
                       jLabel29.setText("電腦放棄");
                       playerbet=computerbetnow+playerbet;
                       computerbet=computerbet-computerbetnow;
                       computerbetnow=0;
                       playerbetnow=0;
                       jLabel6.setText(String.valueOf(playerbet));
                       jLabel28.setText(String.valueOf(computerbet));
                       jButton23.setEnabled(true);
                       jLabel9.setText(null);
                       jLabel21.setText(null);
                   }
                }
               else if(cont==1){
                       jLabel29.setText("電腦放棄");
                       playerbet=computerbetnow+playerbet;
                       computerbet=computerbet-computerbetnow;
                       computerbetnow=0;
                       playerbetnow=0;
                       jLabel6.setText(String.valueOf(playerbet));
                       jLabel28.setText(String.valueOf(computerbet));
                       jButton23.setEnabled(true);
                       jLabel9.setText(null);
                       jLabel21.setText(null);
               }
              
           }
           else if(difficult==2){
               if(cont==3){
                   if(a==b&&c==d&&b==c){//four of akind
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbetnow+20*4;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                   else if((((a==10||b==10||c==10||d==10)&&(a==11||b==11||c==11||d==11)&&(a==12||b==12||c==12||d==12)&&(a==13||b==13||c==13||d==13))||(((a==1||b==1||c==1||d==1)&&(a==11||b==11||c==11||d==11)&&(a==12||b==12||c==12||d==12)&&(a==13||b==13||c==13||d==13)))||(((a==10||b==10||c==10||d==10)&&(a==11||b==11||c==11||d==11)&&(a==12||b==12||c==12||d==12)&&(a==1||b==1||c==1||d==1)))||(((a==10||b==10||c==10||d==10)&&(a==11||b==11||c==11||d==11)&&(a==1||b==1||c==1||d==1)&&(a==13||b==13||c==13||d==13)))||(((a==10||b==10||c==10||d==10)&&(a==1||b==1||c==1||d==1)&&(a==12||b==12||c==12||d==12)&&(a==13||b==13||c==13||d==13))))&&(aa==bb&&cc==dd&&bb==cc)){//royal straight flush
                       if(computerbet<200){
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbetnow+20*4;
                       }
                       else{
                           jLabel29.setText("電腦放棄");
                           playerbet=playerbet+computerbetnow;
                           computerbet=computerbet-computerbetnow;
                           computerbetnow=0;
                           playerbetnow=0;
                           jLabel6.setText(String.valueOf(playerbet));
                           jLabel28.setText(String.valueOf(computerbet));
                           jButton23.setEnabled(true);
                           jLabel9.setText(null);
                           jLabel21.setText(null);
                       }
                   }
                   else if((a==b&&b==c)||(b==c&&c==d)||(a==c&&c==d)||(a==b&&b==d)){//full house or three of a kind or four of a kind
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbetnow+20*4;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                   else if((aa==bb)&&(bb==cc)&&(cc==dd)){
                       //flush
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbetnow+20*4;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                   else if((aa==bb)&&(bb==cc)&&(cc==dd)){//flush
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbetnow+20*4;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                   else{//小牌就放棄不跟//straight也不賭
                       jLabel29.setText("電腦放棄");
                       playerbet=playerbet+computerbetnow;
                       computerbet=computerbet-computerbetnow;
                       computerbetnow=0;
                       playerbetnow=0;
                       jLabel6.setText(String.valueOf(playerbet));
                       jLabel28.setText(String.valueOf(computerbet));
                       jButton23.setEnabled(true);
                       jLabel9.setText(null);
                       jLabel21.setText(null);
                   }
               }
               else if(cont==2){
                   if(a==b&&b==c){//three of kind or four of a kind or full house
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbet+20*4;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                    else if((aa==bb)&&(bb==cc)){//flush
                       jLabel29.setText("電腦跟了");
                       computerbetnow=computerbetnow+20*4;
                       jLabel9.setText(String.valueOf(computerbetnow));
                       computerstatus=1;
                   }
                   else{
                       jLabel29.setText("電腦放棄");
                       playerbet=playerbet+computerbetnow;
                       computerbet=computerbet-computerbetnow;
                       computerbetnow=0;
                       playerbetnow=0;
                       jLabel6.setText(String.valueOf(playerbet));
                       jLabel28.setText(String.valueOf(computerbet));
                       jButton23.setEnabled(true);
                       jLabel9.setText(null);
                       jLabel21.setText(null);
                   }
                }
               else if(cont==1){
                       jLabel29.setText("電腦放棄");
                       playerbet=playerbet*2;
                       computerbet=computerbet-computerbetnow;
                       computerbetnow=0;
                       playerbetnow=0;
                       jLabel6.setText(String.valueOf(playerbet));
                       jLabel28.setText(String.valueOf(computerbet));
                       jButton23.setEnabled(true);
                       jLabel9.setText(null);
                       jLabel21.setText(null);
               }
           }
           else{
               jLabel29.setText("電腦跟了");
               computerbetnow=computerbetnow+20*4;
               jLabel9.setText(String.valueOf(computerbetnow));
               computerstatus=1;
           }
       }
        jButton22.setEnabled(true);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton10.setEnabled(false);
        jButton12.setEnabled(false);
        jButton13.setEnabled(false);
        jButton14.setEnabled(false);
        jButton20.setEnabled(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        //全部歸零開新局
        playerbet=500;computerbet=500;playerbetnow=0;computerbetnow=0;cardcount=0;allin=0;
        jLabel28.setText("500");
        jLabel6.setText("500");
        jLabel9.setText(null);
        jLabel21.setText(null);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton10.setEnabled(false);
        jButton12.setEnabled(false);
        jButton13.setEnabled(false);
        jButton14.setEnabled(false);
        jButton21.setEnabled(false);
        jButton22.setEnabled(false);
        jButton23.setEnabled(false);
        jButton20.setEnabled(false);
        jButton15.setEnabled(true);
        jButton16.setEnabled(true);
        jButton17.setEnabled(true);
        
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
